require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PatientExercisesController do

  # This should return the minimal set of attributes required to create a valid
  # PatientExercise. As you add validations to PatientExercise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "patient_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatientExercisesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all patient_exercises as @patient_exercises" do
      patient_exercise = PatientExercise.create! valid_attributes
      get :index, {}, valid_session
      assigns(:patient_exercises).should eq([patient_exercise])
    end
  end

  describe "GET show" do
    it "assigns the requested patient_exercise as @patient_exercise" do
      patient_exercise = PatientExercise.create! valid_attributes
      get :show, {:id => patient_exercise.to_param}, valid_session
      assigns(:patient_exercise).should eq(patient_exercise)
    end
  end

  describe "GET new" do
    it "assigns a new patient_exercise as @patient_exercise" do
      get :new, {}, valid_session
      assigns(:patient_exercise).should be_a_new(PatientExercise)
    end
  end

  describe "GET edit" do
    it "assigns the requested patient_exercise as @patient_exercise" do
      patient_exercise = PatientExercise.create! valid_attributes
      get :edit, {:id => patient_exercise.to_param}, valid_session
      assigns(:patient_exercise).should eq(patient_exercise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PatientExercise" do
        expect {
          post :create, {:patient_exercise => valid_attributes}, valid_session
        }.to change(PatientExercise, :count).by(1)
      end

      it "assigns a newly created patient_exercise as @patient_exercise" do
        post :create, {:patient_exercise => valid_attributes}, valid_session
        assigns(:patient_exercise).should be_a(PatientExercise)
        assigns(:patient_exercise).should be_persisted
      end

      it "redirects to the created patient_exercise" do
        post :create, {:patient_exercise => valid_attributes}, valid_session
        response.should redirect_to(PatientExercise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved patient_exercise as @patient_exercise" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatientExercise.any_instance.stub(:save).and_return(false)
        post :create, {:patient_exercise => { "patient_id" => "invalid value" }}, valid_session
        assigns(:patient_exercise).should be_a_new(PatientExercise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatientExercise.any_instance.stub(:save).and_return(false)
        post :create, {:patient_exercise => { "patient_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested patient_exercise" do
        patient_exercise = PatientExercise.create! valid_attributes
        # Assuming there are no other patient_exercises in the database, this
        # specifies that the PatientExercise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PatientExercise.any_instance.should_receive(:update_attributes).with({ "patient_id" => "1" })
        put :update, {:id => patient_exercise.to_param, :patient_exercise => { "patient_id" => "1" }}, valid_session
      end

      it "assigns the requested patient_exercise as @patient_exercise" do
        patient_exercise = PatientExercise.create! valid_attributes
        put :update, {:id => patient_exercise.to_param, :patient_exercise => valid_attributes}, valid_session
        assigns(:patient_exercise).should eq(patient_exercise)
      end

      it "redirects to the patient_exercise" do
        patient_exercise = PatientExercise.create! valid_attributes
        put :update, {:id => patient_exercise.to_param, :patient_exercise => valid_attributes}, valid_session
        response.should redirect_to(patient_exercise)
      end
    end

    describe "with invalid params" do
      it "assigns the patient_exercise as @patient_exercise" do
        patient_exercise = PatientExercise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatientExercise.any_instance.stub(:save).and_return(false)
        put :update, {:id => patient_exercise.to_param, :patient_exercise => { "patient_id" => "invalid value" }}, valid_session
        assigns(:patient_exercise).should eq(patient_exercise)
      end

      it "re-renders the 'edit' template" do
        patient_exercise = PatientExercise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatientExercise.any_instance.stub(:save).and_return(false)
        put :update, {:id => patient_exercise.to_param, :patient_exercise => { "patient_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested patient_exercise" do
      patient_exercise = PatientExercise.create! valid_attributes
      expect {
        delete :destroy, {:id => patient_exercise.to_param}, valid_session
      }.to change(PatientExercise, :count).by(-1)
    end

    it "redirects to the patient_exercises list" do
      patient_exercise = PatientExercise.create! valid_attributes
      delete :destroy, {:id => patient_exercise.to_param}, valid_session
      response.should redirect_to(patient_exercises_url)
    end
  end

end
