require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TheoreticalBackgroundsController do

  # This should return the minimal set of attributes required to create a valid
  # TheoreticalBackground. As you add validations to TheoreticalBackground, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TheoreticalBackgroundsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all theoretical_backgrounds as @theoretical_backgrounds" do
      theoretical_background = TheoreticalBackground.create! valid_attributes
      get :index, {}, valid_session
      assigns(:theoretical_backgrounds).should eq([theoretical_background])
    end
  end

  describe "GET show" do
    it "assigns the requested theoretical_background as @theoretical_background" do
      theoretical_background = TheoreticalBackground.create! valid_attributes
      get :show, {:id => theoretical_background.to_param}, valid_session
      assigns(:theoretical_background).should eq(theoretical_background)
    end
  end

  describe "GET new" do
    it "assigns a new theoretical_background as @theoretical_background" do
      get :new, {}, valid_session
      assigns(:theoretical_background).should be_a_new(TheoreticalBackground)
    end
  end

  describe "GET edit" do
    it "assigns the requested theoretical_background as @theoretical_background" do
      theoretical_background = TheoreticalBackground.create! valid_attributes
      get :edit, {:id => theoretical_background.to_param}, valid_session
      assigns(:theoretical_background).should eq(theoretical_background)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TheoreticalBackground" do
        expect {
          post :create, {:theoretical_background => valid_attributes}, valid_session
        }.to change(TheoreticalBackground, :count).by(1)
      end

      it "assigns a newly created theoretical_background as @theoretical_background" do
        post :create, {:theoretical_background => valid_attributes}, valid_session
        assigns(:theoretical_background).should be_a(TheoreticalBackground)
        assigns(:theoretical_background).should be_persisted
      end

      it "redirects to the created theoretical_background" do
        post :create, {:theoretical_background => valid_attributes}, valid_session
        response.should redirect_to(TheoreticalBackground.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved theoretical_background as @theoretical_background" do
        # Trigger the behavior that occurs when invalid params are submitted
        TheoreticalBackground.any_instance.stub(:save).and_return(false)
        post :create, {:theoretical_background => { "id" => "invalid value" }}, valid_session
        assigns(:theoretical_background).should be_a_new(TheoreticalBackground)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TheoreticalBackground.any_instance.stub(:save).and_return(false)
        post :create, {:theoretical_background => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested theoretical_background" do
        theoretical_background = TheoreticalBackground.create! valid_attributes
        # Assuming there are no other theoretical_backgrounds in the database, this
        # specifies that the TheoreticalBackground created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TheoreticalBackground.any_instance.should_receive(:update_attributes).with({ "id" => "1" })
        put :update, {:id => theoretical_background.to_param, :theoretical_background => { "id" => "1" }}, valid_session
      end

      it "assigns the requested theoretical_background as @theoretical_background" do
        theoretical_background = TheoreticalBackground.create! valid_attributes
        put :update, {:id => theoretical_background.to_param, :theoretical_background => valid_attributes}, valid_session
        assigns(:theoretical_background).should eq(theoretical_background)
      end

      it "redirects to the theoretical_background" do
        theoretical_background = TheoreticalBackground.create! valid_attributes
        put :update, {:id => theoretical_background.to_param, :theoretical_background => valid_attributes}, valid_session
        response.should redirect_to(theoretical_background)
      end
    end

    describe "with invalid params" do
      it "assigns the theoretical_background as @theoretical_background" do
        theoretical_background = TheoreticalBackground.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TheoreticalBackground.any_instance.stub(:save).and_return(false)
        put :update, {:id => theoretical_background.to_param, :theoretical_background => { "id" => "invalid value" }}, valid_session
        assigns(:theoretical_background).should eq(theoretical_background)
      end

      it "re-renders the 'edit' template" do
        theoretical_background = TheoreticalBackground.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TheoreticalBackground.any_instance.stub(:save).and_return(false)
        put :update, {:id => theoretical_background.to_param, :theoretical_background => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested theoretical_background" do
      theoretical_background = TheoreticalBackground.create! valid_attributes
      expect {
        delete :destroy, {:id => theoretical_background.to_param}, valid_session
      }.to change(TheoreticalBackground, :count).by(-1)
    end

    it "redirects to the theoretical_backgrounds list" do
      theoretical_background = TheoreticalBackground.create! valid_attributes
      delete :destroy, {:id => theoretical_background.to_param}, valid_session
      response.should redirect_to(theoretical_backgrounds_url)
    end
  end

end
