require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VoiceHygienesController do

  # This should return the minimal set of attributes required to create a valid
  # VoiceHygiene. As you add validations to VoiceHygiene, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VoiceHygienesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all voice_hygienes as @voice_hygienes" do
      voice_hygiene = VoiceHygiene.create! valid_attributes
      get :index, {}, valid_session
      assigns(:voice_hygienes).should eq([voice_hygiene])
    end
  end

  describe "GET show" do
    it "assigns the requested voice_hygiene as @voice_hygiene" do
      voice_hygiene = VoiceHygiene.create! valid_attributes
      get :show, {:id => voice_hygiene.to_param}, valid_session
      assigns(:voice_hygiene).should eq(voice_hygiene)
    end
  end

  describe "GET new" do
    it "assigns a new voice_hygiene as @voice_hygiene" do
      get :new, {}, valid_session
      assigns(:voice_hygiene).should be_a_new(VoiceHygiene)
    end
  end

  describe "GET edit" do
    it "assigns the requested voice_hygiene as @voice_hygiene" do
      voice_hygiene = VoiceHygiene.create! valid_attributes
      get :edit, {:id => voice_hygiene.to_param}, valid_session
      assigns(:voice_hygiene).should eq(voice_hygiene)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VoiceHygiene" do
        expect {
          post :create, {:voice_hygiene => valid_attributes}, valid_session
        }.to change(VoiceHygiene, :count).by(1)
      end

      it "assigns a newly created voice_hygiene as @voice_hygiene" do
        post :create, {:voice_hygiene => valid_attributes}, valid_session
        assigns(:voice_hygiene).should be_a(VoiceHygiene)
        assigns(:voice_hygiene).should be_persisted
      end

      it "redirects to the created voice_hygiene" do
        post :create, {:voice_hygiene => valid_attributes}, valid_session
        response.should redirect_to(VoiceHygiene.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voice_hygiene as @voice_hygiene" do
        # Trigger the behavior that occurs when invalid params are submitted
        VoiceHygiene.any_instance.stub(:save).and_return(false)
        post :create, {:voice_hygiene => { "id" => "invalid value" }}, valid_session
        assigns(:voice_hygiene).should be_a_new(VoiceHygiene)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VoiceHygiene.any_instance.stub(:save).and_return(false)
        post :create, {:voice_hygiene => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voice_hygiene" do
        voice_hygiene = VoiceHygiene.create! valid_attributes
        # Assuming there are no other voice_hygienes in the database, this
        # specifies that the VoiceHygiene created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VoiceHygiene.any_instance.should_receive(:update_attributes).with({ "id" => "1" })
        put :update, {:id => voice_hygiene.to_param, :voice_hygiene => { "id" => "1" }}, valid_session
      end

      it "assigns the requested voice_hygiene as @voice_hygiene" do
        voice_hygiene = VoiceHygiene.create! valid_attributes
        put :update, {:id => voice_hygiene.to_param, :voice_hygiene => valid_attributes}, valid_session
        assigns(:voice_hygiene).should eq(voice_hygiene)
      end

      it "redirects to the voice_hygiene" do
        voice_hygiene = VoiceHygiene.create! valid_attributes
        put :update, {:id => voice_hygiene.to_param, :voice_hygiene => valid_attributes}, valid_session
        response.should redirect_to(voice_hygiene)
      end
    end

    describe "with invalid params" do
      it "assigns the voice_hygiene as @voice_hygiene" do
        voice_hygiene = VoiceHygiene.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VoiceHygiene.any_instance.stub(:save).and_return(false)
        put :update, {:id => voice_hygiene.to_param, :voice_hygiene => { "id" => "invalid value" }}, valid_session
        assigns(:voice_hygiene).should eq(voice_hygiene)
      end

      it "re-renders the 'edit' template" do
        voice_hygiene = VoiceHygiene.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VoiceHygiene.any_instance.stub(:save).and_return(false)
        put :update, {:id => voice_hygiene.to_param, :voice_hygiene => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voice_hygiene" do
      voice_hygiene = VoiceHygiene.create! valid_attributes
      expect {
        delete :destroy, {:id => voice_hygiene.to_param}, valid_session
      }.to change(VoiceHygiene, :count).by(-1)
    end

    it "redirects to the voice_hygienes list" do
      voice_hygiene = VoiceHygiene.create! valid_attributes
      delete :destroy, {:id => voice_hygiene.to_param}, valid_session
      response.should redirect_to(voice_hygienes_url)
    end
  end

end
